Update build_pipeline.yml

diff --git a/.github/workflows/build_pipeline.yml b/.github/workflows/build_pipeline.yml
--- a/.github/workflows/build_pipeline.yml
+++ b/.github/workflows/build_pipeline.yml
@@ -31,3 +31,15 @@ jobs:
       run: |
         cd build
         ctest
+
+
+# This job will run only if the previous jobs fail
+ # This job will run only if the previous jobs fail
+  stop_push:
+    runs-on: ubuntu-latest
+    needs: build
+    if: failure()
+
+    steps:
+    - name: Stop Push and Show Error
+      run: exit 1
